apiVersion: v1
kind: Service
metadata:
  name: githubspot
  namespace: default
spec:
  ports:
  - name: githubspot
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: githubspot
  sessionAffinity: None
  type: ClusterIP
